### ISSUE TITLE
Some words are skipped due to whitespaces

### ISSUE THREAD

**Issue by max-baz** [mortenivar/aspell-da#1]
Hey, I just saw these warnings during the build and wanted to let you know :pray: 

```
==> Starting build()...
Finding Dictionary file location ... /usr/lib/aspell-0.60
Finding Data file location ... /usr/lib/aspell-0.60
cat da.wl | LC_COLLATE=C sort -u | /usr/bin/prezip-bin -z > da.cwl
/usr/bin/prezip-bin -d < da.cwl | /usr/bin/aspell  --lang=da create master ./da.rws
Warning: The word "fil-endelse " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
Warning: The word "himalaya-gran " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
Warning: The word "himalayabirk " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
```

**Comment by mortenivar** [comment]
Hello Maxim

It was fixed in main, but I hadn't made a release. I have done
so now. I also added some new words.

The 4.2 release also contained some erroneous entries that
stemmed from some experiments I did with an extension mode I
have made for the editor I use.

Therefore, I think you should make a new release in Arch
whenever you have the time.

Thanks,
Morten

Maxim Baz ***@***.***> wrote:

> Hey, I just saw these warnings during the build and wanted to let you know :pray: 
> 
> ```
> ==> Starting build()...
> Finding Dictionary file location ... /usr/lib/aspell-0.60
> Finding Data file location ... /usr/lib/aspell-0.60
> cat da.wl | LC_COLLATE=C sort -u | /usr/bin/prezip-bin -z > da.cwl
> /usr/bin/prezip-bin -d < da.cwl | /usr/bin/aspell  --lang=da create master ./da.rws
> Warning: The word "fil-endelse " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
> Warning: The word "himalaya-gran " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
> Warning: The word "himalayabirk " is invalid. The character ' ' (U+20) may not appear at the end of a word. Skipping word.
> ```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mortenivar/aspell-da/issues/1
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 
Morten Bo Johansen

**Comment by max-baz** [comment]
Thanks - and done!
